### Get Embeddings
POST /rest/v1/api/embed/prompt
Host: localhost:8080
Content-Type: application/json
Authorization: Basic system:

{
    "prompt": "There are 7 days in a week."
}


### Make new prompt
POST /rest/v1/api/new/prompt
Host: localhost:8080
Content-Type: application/json
Authorization: Basic system:

{
    "prompt": "When can we perform an internal visual inspection on a piping circuit?"
}

### Chat with phi-3
POST /rest/v1/api/new/prompt/phi3
Host: localhost:8080
Content-Type: application/json
Authorization: Basic system:

{
    "prompt": "When can we perform an internal visual inspection on a piping circuit?"
}

### Make new prompt to evaluate embeddings
POST /rest/v1/api/new/prompt/mistral/evaluate
Host: localhost:8080
Content-Type: application/json
Authorization: Basic system:

{
    "prompt": "How many days are there in a week?"
}

### Load API 570 Data
POST /rest/v1/api/load/api/570/data
Host: localhost:8080
Authorization: Basic system: